<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <!--InternalsVisibleTo -->
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>SnapLineFromChild.Designer.Server</_Parameter1>
      <_Parameter1_TypeName>System.String</_Parameter1_TypeName>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
